name: auto_mock_vocal
description: Another TTS based on Azure.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  desktop_window: ^0.4.0
  expandable: ^5.0.1
  http: ^0.13.4
  input_slider: ^0.3.0
  file_picker: ^4.6.1
  progress_state_button: ^1.0.4
  url_launcher: ^6.1.2
  fluttericon: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
    - voices.json